
//NOTE: NO HEADER GUARD ON PURPOSE! - This file is designed to be included multiple times

#include "PixelTemplateMacros.h"

#ifdef FUNCTION_IGNORE_Yb1
#define FUNCTION_IGNORE_PIXEL_TYPE_1
#endif

#ifdef FUNCTION_IGNORE_Yi1u
#define FUNCTION_IGNORE_PIXEL_TYPE_2
#endif

#ifdef FUNCTION_IGNORE_Yi4
#define FUNCTION_IGNORE_PIXEL_TYPE_3
#endif

#ifdef FUNCTION_IGNORE_RGBi1u
#define FUNCTION_IGNORE_PIXEL_TYPE_4
#endif

#ifdef FUNCTION_IGNORE_RGBi4
#define FUNCTION_IGNORE_PIXEL_TYPE_5
#endif

#ifdef FUNCTION_IGNORE_RGBf8
#define FUNCTION_IGNORE_PIXEL_TYPE_6
#endif

#ifdef FUNCTION_IGNORE_ARGBi1u
#define FUNCTION_IGNORE_PIXEL_TYPE_7
#endif

#ifdef FUNCTION_IGNORE_ARGBi4
#define FUNCTION_IGNORE_PIXEL_TYPE_8
#endif

#ifdef FUNCTION_IGNORE_YUVf8
#define FUNCTION_IGNORE_PIXEL_TYPE_9
#endif


#ifdef ONLY_F

#ifdef FUNCTION_TEMPLATE_RETUR